name: BrokerX

on:
    push:
        branches:
            - main
    pull_request:  
        branches:
            - main
jobs:
    backend:
        name: Go Backend CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                    go-version: "1.25.3+"
            
            - name: Install dependencies
              run: go mod download
            
            - name: Run lint
              run: go vet ./...
            
            - name: Build backend
              run: go build -v 
    frontend:
        name: React Frontend CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                    node-version: "20+"
                    cache: "npm"
                    cache-dependency-path: "frontend/package-lock.json"
            
            - name: Install dependencies
              run: npm ci
              working-directory: ./frontend
              
            - name: Run lint
              run: npm run lint
              working-directory: ./frontend


            - name: Build frontend
              run: npm run build
              working-directory: ./frontend